# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  ListRootDirs_config = debug
endif
ifeq ($(config),release)
  ListRootDirs_config = release
endif

PROJECTS := ListRootDirs

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

ListRootDirs:
ifneq (,$(ListRootDirs_config))
	@echo "==== Building ListRootDirs ($(ListRootDirs_config)) ===="
	@${MAKE} --no-print-directory -C ListRootDirs -f Makefile config=$(ListRootDirs_config)
endif

clean:
	@${MAKE} --no-print-directory -C ListRootDirs -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   ListRootDirs"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"